version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
    - "Status: In Progress"
  milestone: 59
  reviewers:
    - "gklijs"
    - "Morlack"
    - "sandjelkovic"
    - "smcvb"
    - "YvonneCeelie"
# Updates for `master`
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
    - "Status: In Progress"
  milestone: 59
  reviewers:
    - "gklijs"
    - "Morlack"
    - "sandjelkovic"
    - "smcvb"
    - "YvonneCeelie"
# Patch and security updates for patch branches
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
    - "Status: In Progress"
  milestone: 71
  open-pull-requests-limit: 5
  reviewers:
    - "gklijs"
    - "Morlack"
    - "sandjelkovic"
    - "smcvb"
    - "YvonneCeelie"
  target-branch: "axon-4.5.x"