version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: [ major, minor ]
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
    - "Status: In Progress"
    - "Target: 4.5.2"
  milestone: 62
  open-pull-requests-limit: 5
  reviewers:
    - "lfgcampos"
    - "m1l4n54v1c"
    - "saratry"
    - "smcvb"
  target-branch: axon-4.5.x