name: Add Dependabot PR's to project

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add dependabot pr to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/AxonFramework/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: 'Type: Dependency Upgrade'
