# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.extract-version-and-notes.outputs.RELEASE_NOTES_FILE }}
      version: ${{ steps.extract-version-and-notes.outputs.VERSION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release Notes Markdown
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"

    - name: Get the name of the created Release Notes file and extract Version
      id: extract-version-and-notes
      run: |
        RELEASE_NOTES_FILE=$(ls temp_release_notes/*.md | head -n 1)
        echo "RELEASE_NOTES_FILE=$RELEASE_NOTES_FILE" >> $GITHUB_ENV
        echo "RELEASE_NOTES_FILE=$RELEASE_NOTES_FILE" >> $GITHUB_OUTPUT
        VERSION=$(echo ${{ github.event.milestone.title }} | cut -d' ' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Create a Draft Release Notes on GitHub
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: axon-${{ env.VERSION }}
        release_name:  Axon Framework v${{ env.VERSION }}
        body_path: ${{ env.RELEASE_NOTES_FILE }}
        draft: true

  trigger-discuss-notification:
    uses: AxonFramework/AxonFramework/.github/workflows/discuss-notification.yml@master
    needs: create-release-notes
    with:
      release_name: Axon Framework - Release ${{ needs.create-release-notes.outputs.version }}
      release_notes_file: ${{ needs.create-release-notes.outputs.notes }}
      release_date: ${{ github.event.milestone.closedAt }}

